---
- name: Install PHP MYSQL
  ansible.builtin.apt:
    name: php-mysql
    state: present
  notify: Restart Apache

- name: Check status
  ansible.builtin.command: php -m
  register: php_modules
  changed_when: false

- name: Print php-mysql status
  ansible.builtin.debug:
    msg: "php-mysql status is {{ 'loaded' if 'mysqli' in php_modules.stdout else 'not loaded' }}"

    