---
galaxy_info:
  author: aram304
  role_name: apache
  description: Installeert en configureert Apache
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - apache
    - webserver
    - linux

dependencies: []
