---
- name: Install PHP
  ansible.builtin.apt:
    name: php
    state: present

- name: Check status
  ansible.builtin.command: php -v
  register: php_status
  changed_when: false

- name: Print PHP status
  debug:
    msg: "PHP is {{ php_status.stdout }}"


